-- MySQL Script generated by MySQL Workbench
-- Fri Jan  5 13:04:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema APPES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema APPES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `APPES` DEFAULT CHARACTER SET utf8 ;
USE `APPES` ;

-- -----------------------------------------------------
-- Table `APPES`.`Danger_Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Danger_Level` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Danger_Level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Diet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Diet` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Diet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Species` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Species` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `scientific_name` VARCHAR(100) NULL,
  `wingspan` TINYINT NULL,
  `withers_height` TINYINT NULL,
  `color` VARCHAR(45) NULL,
  `life_esperancy` TINYINT NULL,
  `description` VARCHAR(255) NULL,
  `tendancy` VARCHAR(45) NULL,
  `clrf` VARCHAR(45) NULL,
  `clrm` VARCHAR(45) NULL,
  `Danger_Level_id` INT NOT NULL,
  `Diet_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Danger_Level_id`, `Diet_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Species_Danger_Level1_idx` (`Danger_Level_id` ASC) VISIBLE,
  INDEX `fk_Species_Diet1_idx` (`Diet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Species_Danger_Level1`
    FOREIGN KEY (`Danger_Level_id`)
    REFERENCES `APPES`.`Danger_Level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Species_Diet1`
    FOREIGN KEY (`Diet_id`)
    REFERENCES `APPES`.`Diet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Regions` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Departments` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Regions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Regions_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Departments_Regions1_idx` (`Regions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Departments_Regions1`
    FOREIGN KEY (`Regions_id`)
    REFERENCES `APPES`.`Regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Associations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Associations` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Associations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `street_number` INT NULL,
  `street_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip_code` VARCHAR(10) NULL,
  `phone_number` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Categories` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Species_has_Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Species_has_Departments` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Species_has_Departments` (
  `Species_id` INT NOT NULL,
  `Departments_id` INT NOT NULL,
  PRIMARY KEY (`Species_id`, `Departments_id`),
  INDEX `fk_Species_has_Departments_Departments1_idx` (`Departments_id` ASC) VISIBLE,
  INDEX `fk_Species_has_Departments_Species_idx` (`Species_id` ASC) VISIBLE,
  CONSTRAINT `fk_Species_has_Departments_Species`
    FOREIGN KEY (`Species_id`)
    REFERENCES `APPES`.`Species` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Species_has_Departments_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `APPES`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Categories_has_Species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Categories_has_Species` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Categories_has_Species` (
  `Categories_id` INT NOT NULL,
  `Species_id` INT NOT NULL,
  PRIMARY KEY (`Categories_id`, `Species_id`),
  INDEX `fk_Categories_has_Species_Species1_idx` (`Species_id` ASC) VISIBLE,
  INDEX `fk_Categories_has_Species_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_has_Species_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `APPES`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Species_Species1`
    FOREIGN KEY (`Species_id`)
    REFERENCES `APPES`.`Species` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Associations_has_Species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Associations_has_Species` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Associations_has_Species` (
  `Associations_id` INT NOT NULL,
  `Species_id` INT NOT NULL,
  PRIMARY KEY (`Associations_id`, `Species_id`),
  INDEX `fk_Associations_has_Species_Species1_idx` (`Species_id` ASC) VISIBLE,
  INDEX `fk_Associations_has_Species_Associations1_idx` (`Associations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Associations_has_Species_Associations1`
    FOREIGN KEY (`Associations_id`)
    REFERENCES `APPES`.`Associations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Associations_has_Species_Species1`
    FOREIGN KEY (`Species_id`)
    REFERENCES `APPES`.`Species` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APPES`.`Associations_has_Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APPES`.`Associations_has_Departments` ;

CREATE TABLE IF NOT EXISTS `APPES`.`Associations_has_Departments` (
  `Associations_id` INT NOT NULL,
  `Departments_id` INT NOT NULL,
  PRIMARY KEY (`Associations_id`, `Departments_id`),
  INDEX `fk_Associations_has_Departments_Departments1_idx` (`Departments_id` ASC) VISIBLE,
  INDEX `fk_Associations_has_Departments_Associations1_idx` (`Associations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Associations_has_Departments_Associations1`
    FOREIGN KEY (`Associations_id`)
    REFERENCES `APPES`.`Associations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Associations_has_Departments_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `APPES`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
